# Generated by Django 3.2.9 on 2021-11-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
